// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "swagger": "2.0",
    "info": {
        "description": "API do OrthoTrack IoT Platform v3 - Sistema de monitoramento de coletes ortopédicos",
        "title": "OrthoTrack IoT API",
        "contact": {
            "name": "API Support",
            "email": "support@orthotrack.com"
        },
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "3.0.0"
    },
    "host": "72.60.50.248:8080",
    "basePath": "/api/v1",
    "schemes": ["http", "https"],
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "paths": {}
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.0.0",
	Host:             "72.60.50.248:8080",
	BasePath:         "/api/v1",
	Schemes:          []string{"http", "https"},
	Title:            "OrthoTrack IoT API",
	Description:      "API do OrthoTrack IoT Platform v3 - Sistema de monitoramento de coletes ortopédicos",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}













